# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  - g++
  
# Build steps
script:
  - mkdir build
  - cd build
  - cmake ..
  - make CMinPack
  - cmake ..
  - make
